modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "savethehorse"
version = "${version}"
displayName = "SaveTheHorse"
authors = "Kall"
description = '''
'''
#logoFile = ""